name: mitx35
channels:
  - conda-forge/label/cf202003
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.3=pyh8c360ce_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - colorama=0.4.3=py_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.2.3=py35_2
  - icu=58.2=ha925a31_3
  - ipykernel=5.1.0=pyh24bf2e0_0
  - ipython=7.0.1=py35h39e3cac_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.12.1=py35_0
  - jinja2=2.11.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - jsonschema=2.6.0=py35_2
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.5.0=py_0
  - libpng=1.6.37=hfe6a214_1
  - libsodium=1.0.17=h2fa13f4_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py35hfa6e2cd_1
  - matplotlib=2.0.2=np113py35_0
  - mistune=0.8.3=py35hfa6e2cd_2
  - mkl=2017.0.3=0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.0=py_0
  - nbformat=5.0.4=py_0
  - notebook=5.7.0=py35_0
  - openssl=1.0.2u=hfa6e2cd_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - pickleshare=0.7.5=py35_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.6.0=py35h764d66f_7
  - python=3.5.6=he025d50_0
  - pywinpty=0.5.4=py35_2
  - pyzmq=17.1.2=py35hf576995_0
  - qt=5.6.2=vc14h6f8c307_12
  - qtconsole=4.7.1=py_0
  - qtpy=1.9.0=py_0
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py_1
  - sip=4.18.1=py35h6538335_0
  - sqlite=3.30.1=hfa6e2cd_0
  - terminado=0.8.1=py35_1
  - testpath=0.4.4=py_0
  - tk=8.5.19=vc10_0
  - tornado=5.1.1=py35hfa6e2cd_0
  - traitlets=4.3.2=py35_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=pyh9f0ad1d_3
  - win_unicode_console=0.5=py35_0
  - wincertstore=0.2=py35hfebbdb8_0
  - winpty=0.4.3=4
  - zeromq=4.2.5=he025d50_4
  - zlib=1.2.11=h2fa13f4_1006
  - pip:
      - numpy==1.18.5
      - pandas==0.25.3
      - pip==20.3.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==301
      - scipy==1.4.1
      - setuptools==49.6.0
      - six==1.17.0
prefix: C:\Users\britt\anaconda3\envs\mitx35
