[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "berkeley-ext-calculus-I"
version = "0.0.0"
dependencies = ["sympy", "numpy", "matplotlib"]

[tool.setuptools]
packages = ["mylib"]